Script started on 2017年03月14日 (週二) 00時56分04秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop $[00m whoami:[K; pwd
pd2vm
/home/pd2vm/Desktop
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop $[00m git config -;[Kl
user.email=sugar.14387@gmail.com
user.name=tyt0429
push.default=matching
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.orgin.url=https://github.com/tyt0429/lab1.git
remote.orgin.fetch=+refs/heads/*:refs/remotes/orgin/*
remote.origin.url=https://github.com/tyt0429/lab1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop $[00m git clone https://git [Khub.com/tyt0429/lab1.git [A
Cloning into 'lab1'...
remote: Counting objects: 5, done.[K
remote: Compressing objects:  33% (1/3)   [Kremote: Compressing objects:  66% (2/3)   [Kremote: Compressing objects: 100% (3/3)   [Kremote: Compressing objects: 100% (3/3), done.[K
remote: Total 5 (delta 0), reused 5 (delta 0), pack-reused 0[K
Unpacking objects:  20% (1/5)   Unpacking objects:  40% (2/5)   Unpacking objects:  60% (3/5)   Unpacking objects:  80% (4/5)   Unpacking objects: 100% (5/5)   Unpacking objects: 100% (5/5), done.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~/Desktop $[00m exit

Script done on 2017年03月14日 (週二) 00時57分40秒
